services:
  db:
    image: postgres:17
    working_dir: /app
    volumes:
      - db-data:/var/lib/postgresql/data
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lakehouse
    ports:
      - "5432:5432"
  dbt:
    build: .
    user: "${UID}:${GID}"
    working_dir: /app/manufacturing_lakehouse_platform
    environment:
      PYTHONPATH: /app/manufacturing_lakehouse_platform
      HOME: /home
    depends_on:
      - db
    volumes:
      - ./:/app
      - ~/.dbt:/home/.dbt
volumes:
  db-data: