services:
  db:
    image: postgres:17
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./datasets:/datasets
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lakehouse
    ports:
      - "5432:5432"
  dbt:
    build: .
    environment:
      PYTHONPATH: /app
    depends_on:
      - db
    volumes:
      - ./:/app
volumes:
  db-data: